In [4]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('ipl.csv')
print(df)

          id   season        city       date match_type player_of_match  \
0     335982  2007/08   Bangalore  4/18/2008     League     BB McCullum
1     335983  2007/08  Chandigarh  4/19/2008     League      MEK Hussey
2     335984  2007/08       Delhi  4/19/2008     League     MF Maharoof
3     335985  2007/08      Mumbai  4/20/2008     League      MV Boucher
4     335986  2007/08     Kolkata  4/20/2008     League       DJ Hussey
..       ...      ...         ...        ...        ...             ...
699  1175359     2019      Jaipur  3/25/2019     League        CH Gayle
700  1175360     2019       Delhi  3/26/2019     League       SR Watson
701  1175361     2019     Kolkata  3/27/2019     League      AD Russell
702  1175362     2019   Bengaluru  3/28/2019     League       JJ Bumrah
703  1175363     2019   Hyderabad  3/29/2019     League     Rashid Khan

                                          venue                        team1  \
0                         M Chinnaswamy Stadium  Royal Challengers Bangalore
1    Punjab Cricket Association Stadium, Mohali              Kings XI Punjab
2                              Feroz Shah Kotla             Delhi Daredevils
3                              Wankhede Stadium               Mumbai Indians
4                                  Eden Gardens        Kolkata Knight Riders
..                                          ...                          ...
699                      Sawai Mansingh Stadium              Kings XI Punjab
700                        Arun Jaitley Stadium               Delhi Capitals
701                                Eden Gardens        Kolkata Knight Riders
702                       M.Chinnaswamy Stadium               Mumbai Indians
703          Rajiv Gandhi International Stadium             Rajasthan Royals

                           team2                  toss_winner toss_decision  \
0          Kolkata Knight Riders  Royal Challengers Bangalore         field
1            Chennai Super Kings          Chennai Super Kings           bat
2               Rajasthan Royals             Rajasthan Royals           bat
3    Royal Challengers Bangalore               Mumbai Indians           bat
4                Deccan Chargers              Deccan Chargers           bat
..                           ...                          ...           ...
699             Rajasthan Royals             Rajasthan Royals         field
700          Chennai Super Kings               Delhi Capitals           bat
701              Kings XI Punjab              Kings XI Punjab         field
702  Royal Challengers Bangalore  Royal Challengers Bangalore         field
703          Sunrisers Hyderabad             Rajasthan Royals           bat

                          winner   result  result_margin  target_runs  \
0          Kolkata Knight Riders     runs          140.0        223.0
1            Chennai Super Kings     runs           33.0        241.0
2               Delhi Daredevils  wickets            9.0        130.0
3    Royal Challengers Bangalore  wickets            5.0        166.0
4          Kolkata Knight Riders  wickets            5.0        111.0
..                           ...      ...            ...          ...
699              Kings XI Punjab     runs           14.0        185.0
700          Chennai Super Kings  wickets            6.0        148.0
701        Kolkata Knight Riders     runs           28.0        219.0
702               Mumbai Indians     runs            6.0        188.0
703          Sunrisers Hyderabad  wickets            5.0        199.0

     target_overs super_over method        umpire1                umpire2
0            20.0          N    NaN      Asad Rauf            RE Koertzen
1            20.0          N    NaN      MR Benson             SL Shastri
2            20.0          N    NaN      Aleem Dar         GA Pratapkumar
3            20.0          N    NaN       SJ Davis              DJ Harper
4            20.0          N    NaN      BF Bowden            K Hariharan
..            ...        ...    ...            ...                    ...
699          20.0          N    NaN  C Shamshuddin  KN Ananthapadmanabhan
700          20.0          N    NaN      M Erasmus            Nitin Menon
701          20.0          N    NaN   AK Chaudhary            VA Kulkarni
702          20.0          N    NaN      CK Nandan                 S Ravi
703          20.0          N    NaN   BNJ Oxenford          C Shamshuddin

[704 rows x 20 columns]

In [23]:
df.head(10)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,4/18/2008,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,4/19/2008,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,4/19/2008,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,4/20/2008,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,4/20/2008,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
5,335987,2007/08,Jaipur,4/21/2008,League,SR Watson,Sawai Mansingh Stadium,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,bat,Rajasthan Royals,wickets,6.0,167.0,20.0,N,NaN,Aleem Dar,RB Tiffin
6,335988,2007/08,Hyderabad,4/22/2008,League,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,Delhi Daredevils,wickets,9.0,143.0,20.0,N,NaN,IL Howell,AM Saheba
7,335989,2007/08,Chennai,4/23/2008,League,ML Hayden,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,6.0,209.0,20.0,N,NaN,DJ Harper,GA Pratapkumar
8,335990,2007/08,Hyderabad,4/24/2008,League,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,3.0,215.0,20.0,N,NaN,Asad Rauf,MR Benson
9,335991,2007/08,Chandigarh,4/25/2008,League,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,Kings XI Punjab,runs,66.0,183.0,20.0,N,NaN,Aleem Dar,AM Saheba

In [24]:
df.tail(10)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
694,1136619,2018,Kolkata,5/25/2018,Qualifier 2,Rashid Khan,Eden Gardens,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,Sunrisers Hyderabad,runs,14.0,175.0,20.0,N,NaN,HDPK Dharmasena,Nitin Menon
695,1136620,2018,Mumbai,5/27/2018,Final,SR Watson,Wankhede Stadium,Sunrisers Hyderabad,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,8.0,179.0,20.0,N,NaN,M Erasmus,S Ravi
696,1175356,2019,Chennai,3/23/2019,League,Harbhajan Singh,MA Chidambaram Stadium,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,7.0,71.0,20.0,N,NaN,AY Dandekar,BNJ Oxenford
697,1175357,2019,Kolkata,3/24/2019,League,AD Russell,Eden Gardens,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,wickets,6.0,182.0,20.0,N,NaN,AK Chaudhary,CB Gaffaney
698,1175358,2019,Mumbai,3/24/2019,League,RR Pant,Wankhede Stadium,Delhi Capitals,Mumbai Indians,Mumbai Indians,field,Delhi Capitals,runs,37.0,214.0,20.0,N,NaN,S Ravi,YC Barde
699,1175359,2019,Jaipur,3/25/2019,League,CH Gayle,Sawai Mansingh Stadium,Kings XI Punjab,Rajasthan Royals,Rajasthan Royals,field,Kings XI Punjab,runs,14.0,185.0,20.0,N,NaN,C Shamshuddin,KN Ananthapadmanabhan
700,1175360,2019,Delhi,3/26/2019,League,SR Watson,Arun Jaitley Stadium,Delhi Capitals,Chennai Super Kings,Delhi Capitals,bat,Chennai Super Kings,wickets,6.0,148.0,20.0,N,NaN,M Erasmus,Nitin Menon
701,1175361,2019,Kolkata,3/27/2019,League,AD Russell,Eden Gardens,Kolkata Knight Riders,Kings XI Punjab,Kings XI Punjab,field,Kolkata Knight Riders,runs,28.0,219.0,20.0,N,NaN,AK Chaudhary,VA Kulkarni
702,1175362,2019,Bengaluru,3/28/2019,League,JJ Bumrah,M.Chinnaswamy Stadium,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Mumbai Indians,runs,6.0,188.0,20.0,N,NaN,CK Nandan,S Ravi
703,1175363,2019,Hyderabad,3/29/2019,League,Rashid Khan,Rajiv Gandhi International Stadium,Rajasthan Royals,Sunrisers Hyderabad,Rajasthan Royals,bat,Sunrisers Hyderabad,wickets,5.0,199.0,20.0,N,NaN,BNJ Oxenford,C Shamshuddin

In [29]:
df.count()

id                 704
season             704
city               691
date               704
match_type         704
player_of_match    701
venue              704
team1              704
team2              704
toss_winner        704
toss_decision      704
winner             701
result             704
result_margin      694
target_runs        702
target_overs       702
super_over         704
method              19
umpire1            704
umpire2            704
dtype: int64

In [31]:
df.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [32]:
df.groupby('city').size()

city
Abu Dhabi          7
Ahmedabad         12
Bangalore         65
Bengaluru          9
Bloemfontein       2
Cape Town          7
Centurion         12
Chandigarh        49
Chennai           50
Cuttack            7
Delhi             68
Dharamsala         9
Durban            15
East London        3
Hyderabad         57
Indore             9
Jaipur            41
Johannesburg       8
Kanpur             4
Kimberley          3
Kochi              5
Kolkata           72
Mumbai            95
Nagpur             3
Port Elizabeth     7
Pune              38
Raipur             6
Rajkot            10
Ranchi             7
Visakhapatnam     11
dtype: int64

In [33]:
df.groupby('season').size()

season
2007/08    58
2009       57
2009/10    60
2011       73
2012       74
2013       76
2014       60
2015       59
2016       60
2017       59
2018       60
2019        8
dtype: int64

In [34]:
df[df['toss_winner']==df['winner']]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
1,335983,2007/08,Chandigarh,4/19/2008,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
8,335990,2007/08,Hyderabad,4/24/2008,League,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,3.0,215.0,20.0,N,NaN,Asad Rauf,MR Benson
10,335992,2007/08,Bangalore,4/26/2008,League,SR Watson,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,7.0,136.0,20.0,N,NaN,MR Benson,IL Howell
12,335994,2007/08,Mumbai,4/27/2008,League,AC Gilchrist,Dr DY Patil Sports Academy,Mumbai Indians,Deccan Chargers,Deccan Chargers,field,Deccan Chargers,wickets,10.0,155.0,20.0,N,NaN,Asad Rauf,SL Shastri
14,335996,2007/08,Bangalore,4/28/2008,League,MS Dhoni,M Chinnaswamy Stadium,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,13.0,179.0,20.0,N,NaN,BR Doctrove,RB Tiffin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,1136616,2018,Pune,5/20/2018,League,L Ngidi,Maharashtra Cricket Association Stadium,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,5.0,154.0,20.0,N,NaN,Nitin Menon,YC Barde
692,1136617,2018,Mumbai,5/22/2018,Qualifier 1,F du Plessis,Wankhede Stadium,Sunrisers Hyderabad,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,2.0,140.0,20.0,N,NaN,C Shamshuddin,M Erasmus
695,1136620,2018,Mumbai,5/27/2018,Final,SR Watson,Wankhede Stadium,Sunrisers Hyderabad,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,8.0,179.0,20.0,N,NaN,M Erasmus,S Ravi
696,1175356,2019,Chennai,3/23/2019,League,Harbhajan Singh,MA Chidambaram Stadium,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,7.0,71.0,20.0,N,NaN,AY Dandekar,BNJ Oxenford
697,1175357,2019,Kolkata,3/24/2019,League,AD Russell,Eden Gardens,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,wickets,6.0,182.0,20.0,N,NaN,AK Chaudhary,CB Gaffaney

In [36]:
df.groupby('winner').size().sort_values(ascending=False)

winner
Mumbai Indians                 99
Chennai Super Kings            92
Kolkata Knight Riders          88
Royal Challengers Bangalore    79
Kings XI Punjab                77
Rajasthan Royals               70
Delhi Daredevils               67
Sunrisers Hyderabad            53
Deccan Chargers                29
Gujarat Lions                  13
Pune Warriors                  12
Rising Pune Supergiant         10
Kochi Tuskers Kerala            6
Rising Pune Supergiants         5
Delhi Capitals                  1
dtype: int64

In [38]:
df[df["result_margin"] > 50]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,4/18/2008,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
9,335991,2007/08,Chandigarh,4/25/2008,League,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,Kings XI Punjab,runs,66.0,183.0,20.0,N,NaN,Aleem Dar,AM Saheba
39,336023,2007/08,Jaipur,5/17/2008,League,GC Smith,Sawai Mansingh Stadium,Rajasthan Royals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Rajasthan Royals,runs,65.0,198.0,20.0,N,NaN,BF Bowden,SL Shastri
55,336038,2007/08,Mumbai,5/30/2008,Semi Final,SR Watson,Wankhede Stadium,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,field,Rajasthan Royals,runs,105.0,193.0,20.0,N,NaN,BF Bowden,RE Koertzen
59,392182,2009,Cape Town,4/18/2009,League,R Dravid,Newlands,Royal Challengers Bangalore,Rajasthan Royals,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,75.0,134.0,20.0,N,NaN,BR Doctrove,RB Tiffin
62,392185,2009,Port Elizabeth,4/20/2009,League,M Muralitharan,St George's Park,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,92.0,180.0,20.0,N,NaN,BG Jerling,SJA Taufel
72,392197,2009,Port Elizabeth,4/27/2009,League,SR Tendulkar,St George's Park,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,bat,Mumbai Indians,runs,92.0,188.0,20.0,N,NaN,BG Jerling,RB Tiffin
84,392209,2009,East London,5/4/2009,League,MS Dhoni,Buffalo Park,Chennai Super Kings,Deccan Chargers,Chennai Super Kings,bat,Chennai Super Kings,runs,78.0,179.0,20.0,N,NaN,BR Doctrove,M Erasmus
85,392210,2009,Durban,5/5/2009,League,GC Smith,Kingsmead,Kings XI Punjab,Rajasthan Royals,Kings XI Punjab,field,Rajasthan Royals,runs,78.0,212.0,20.0,N,NaN,SS Hazare,IL Howell
95,392220,2009,Kimberley,5/11/2009,League,DR Smith,De Beers Diamond Oval,Deccan Chargers,Rajasthan Royals,Deccan Chargers,bat,Deccan Chargers,runs,53.0,167.0,20.0,N,NaN,GAV Baxter,HDPK Dharmasena
122,419113,2009/10,Kolkata,3/16/2010,League,MS Dhoni,Eden Gardens,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,55.0,165.0,20.0,N,NaN,HDPK Dharmasena,AM Saheba
123,419114,2009/10,Delhi,3/17/2010,League,SR Tendulkar,Feroz Shah Kotla,Delhi Daredevils,Mumbai Indians,Delhi Daredevils,field,Mumbai Indians,runs,98.0,219.0,20.0,N,NaN,BR Doctrove,SK Tarapore
143,419134,2009/10,Delhi,3/31/2010,League,KD Karthik,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,bat,Delhi Daredevils,runs,67.0,189.0,20.0,N,NaN,HDPK Dharmasena,SJA Taufel
147,419138,2009/10,Mumbai,4/3/2010,League,AT Rayudu,Brabourne Stadium,Mumbai Indians,Deccan Chargers,Mumbai Indians,bat,Mumbai Indians,runs,63.0,179.0,20.0,N,NaN,BR Doctrove,S Ravi
166,419157,2009/10,Bangalore,4/17/2010,League,R McLaren,M Chinnaswamy Stadium,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,field,Mumbai Indians,runs,57.0,192.0,20.0,N,NaN,HDPK Dharmasena,SJA Taufel
205,501229,2011,Kochi,4/27/2011,League,I Sharma,Nehru Stadium,Kochi Tuskers Kerala,Deccan Chargers,Kochi Tuskers Kerala,field,Deccan Chargers,runs,55.0,130.0,20.0,N,NaN,HDPK Dharmasena,AL Hill
220,501244,2011,Bangalore,5/6/2011,League,CH Gayle,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,Royal Challengers Bangalore,runs,85.0,206.0,20.0,N,NaN,Aleem Dar,RB Tiffin
225,501249,2011,Jaipur,5/9/2011,League,M Vijay,Sawai Mansingh Stadium,Rajasthan Royals,Chennai Super Kings,Rajasthan Royals,field,Chennai Super Kings,runs,63.0,197.0,20.0,N,NaN,K Hariharan,SJA Taufel
227,501251,2011,Chandigarh,5/10/2011,League,BA Bhatt,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,Kings XI Punjab,runs,76.0,164.0,20.0,N,NaN,SK Tarapore,RJ Tucker
236,501260,2011,Dharamsala,5/17/2011,League,AC Gilchrist,Himachal Pradesh Cricket Association Stadium,Kings XI Punjab,Royal Challengers Bangalore,Kings XI Punjab,bat,Kings XI Punjab,runs,111.0,233.0,20.0,N,NaN,Asad Rauf,AM Saheba
240,501264,2011,Dharamsala,5/21/2011,League,S Dhawan,Himachal Pradesh Cricket Association Stadium,Kings XI Punjab,Deccan Chargers,Kings XI Punjab,field,Deccan Chargers,runs,82.0,199.0,20.0,N,NaN,Asad Rauf,AM Saheba
247,501271,2011,Chennai,5/28/2011,Final,M Vijay,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings,bat,Chennai Super Kings,runs,58.0,206.0,20.0,N,NaN,Asad Rauf,SJA Taufel
253,548311,2012,Visakhapatnam,4/7/2012,League,RA Jadeja,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Deccan Chargers,Chennai Super Kings,Deccan Chargers,field,Chennai Super Kings,runs,74.0,194.0,20.0,N,NaN,JD Cloete,HDPK Dharmasena
265,548324,2012,Bangalore,4/15/2012,League,AM Rahane,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,bat,Rajasthan Royals,runs,59.0,196.0,20.0,N,NaN,JD Cloete,RJ Tucker
320,548380,2012,Chennai,5/25/2012,Qualifier 2,M Vijay,"MA Chidambaram Stadium, Chepauk",Delhi Daredevils,Chennai Super Kings,Delhi Daredevils,field,Chennai Super Kings,runs,86.0,223.0,20.0,N,NaN,BR Doctrove,SJA Taufel
344,598019,2013,Jaipur,4/17/2013,League,AM Rahane,Sawai Mansingh Stadium,Rajasthan Royals,Mumbai Indians,Rajasthan Royals,bat,Rajasthan Royals,runs,87.0,180.0,20.0,N,NaN,Aleem Dar,C Shamshuddin
345,598020,2013,Delhi,4/18/2013,League,MEK Hussey,Feroz Shah Kotla,Delhi Daredevils,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,86.0,170.0,20.0,N,NaN,M Erasmus,VA Kulkarni
352,598027,2013,Bangalore,4/23/2013,League,CH Gayle,M Chinnaswamy Stadium,Royal Challengers Bangalore,Pune Warriors,Pune Warriors,field,Royal Challengers Bangalore,runs,130.0,264.0,20.0,N,NaN,Aleem Dar,C Shamshuddin
358,598033,2013,Mumbai,4/27/2013,League,DR Smith,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Mumbai Indians,runs,58.0,195.0,20.0,N,NaN,Asad Rauf,S Asnani
370,598046,2013,Mumbai,5/5/2013,League,MG Johnson,Wankhede Stadium,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Mumbai Indians,runs,60.0,140.0,20.0,N,NaN,HDPK Dharmasena,CK Nandan
374,598050,2013,Mumbai,5/7/2013,League,SR Tendulkar,Wankhede Stadium,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,bat,Mumbai Indians,runs,65.0,171.0,20.0,N,NaN,HDPK Dharmasena,S Ravi
375,598051,2013,Hyderabad,5/8/2013,League,SK Raina,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,field,Chennai Super Kings,runs,77.0,224.0,20.0,N,NaN,S Das,NJ Llong
405,729293,2014,Abu Dhabi,4/21/2014,League,SK Raina,Sheikh Zayed Stadium,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings,bat,Chennai Super Kings,runs,93.0,178.0,20.0,N,NaN,RK Illingworth,C Shamshuddin
406,729295,2014,NaN,4/22/2014,League,GJ Maxwell,Sharjah Cricket Stadium,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kings XI Punjab,runs,72.0,194.0,20.0,N,NaN,M Erasmus,S Ravi
438,734011,2014,Ahmedabad,5/15/2014,League,AM Rahane,"Sardar Patel Stadium, Motera",Rajasthan Royals,Delhi Daredevils,Delhi Daredevils,field,Rajasthan Royals,runs,62.0,202.0,20.0,N,NaN,S Ravi,RJ Tucker
481,829753,2015,Chennai,4/25/2015,League,BB McCullum,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,Chennai Super Kings,runs,97.0,193.0,20.0,N,NaN,JD Cloete,C Shamshuddin
496,829785,2015,Bangalore,5/6/2015,League,CH Gayle,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,Royal Challengers Bangalore,runs,138.0,227.0,20.0,N,NaN,RK Illingworth,VA Kulkarni
514,829819,2015,Pune,5/20/2015,Eliminator,AB de Villiers,Maharashtra Cricket Association Stadium,Royal Challengers Bangalore,Rajasthan Royals,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,71.0,181.0,20.0,N,NaN,AK Chaudhary,C Shamshuddin
553,980973,2016,Visakhapatnam,5/8/2016,League,A Nehra,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,field,Sunrisers Hyderabad,runs,85.0,178.0,20.0,N,NaN,S Ravi,C Shamshuddin
560,980987,2016,Bangalore,5/14/2016,League,AB de Villiers,M Chinnaswamy Stadium,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,field,Royal Challengers Bangalore,runs,144.0,249.0,20.0,N,NaN,AY Dandekar,VK Sharma
563,980993,2016,Visakhapatnam,5/15/2016,League,KH Pandya,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,Mumbai Indians,runs,80.0,207.0,20.0,N,NaN,Nitin Menon,CK Nandan
566,980999,2016,Bangalore,5/18/2016,League,V Kohli,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,Royal Challengers Bangalore,runs,82.0,203.0,14.0,N,D/L,KN Ananthapadmanabhan,M Erasmus
585,1082599,2017,Pune,4/11/2017,League,SV Samson,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,Delhi Daredevils,Rising Pune Supergiant,field,Delhi Daredevils,runs,97.0,206.0,20.0,N,NaN,AY Dandekar,S Ravi
591,1082605,2017,Delhi,4/15/2017,League,CJ Anderson,Feroz Shah Kotla,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,Delhi Daredevils,runs,51.0,189.0,20.0,N,NaN,YC Barde,Nitin Menon
603,1082617,2017,Kolkata,4/23/2017,League,NM Coulter-Nile,Eden Gardens,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,82.0,132.0,20.0,N,NaN,CB Gaffaney,CK Nandan
609,1082624,2017,Pune,4/29/2017,League,LH Ferguson,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Rising Pune Supergiant,runs,61.0,158.0,20.0,N,NaN,KN Ananthapadmanabhan,M Erasmus
620,1082635,2017,Delhi,5/6/2017,League,LMP Simmons,Feroz Shah Kotla,Delhi Daredevils,Mumbai Indians,Delhi Daredevils,field,Mumbai Indians,runs,146.0,213.0,20.0,N,NaN,Nitin Menon,CK Nandan
648,1136573,2018,Kolkata,4/16/2018,League,N Rana,Eden Gardens,Kolkata Knight Riders,Delhi Daredevils,Delhi Daredevils,field,Kolkata Knight Riders,runs,71.0,201.0,20.0,N,NaN,AK Chaudhary,A Nand Kishore
652,1136577,2018,Pune,4/20/2018,League,SR Watson,Maharashtra Cricket Association Stadium,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,Chennai Super Kings,runs,64.0,205.0,20.0,N,NaN,KN Ananthapadmanabhan,Nitin Menon
661,1136586,2018,Delhi,4/27/2018,League,SS Iyer,Arun Jaitley Stadium,Delhi Daredevils,Kolkata Knight Riders,Kolkata Knight Riders,field,Delhi Daredevils,runs,55.0,220.0,20.0,N,NaN,C Shamshuddin,S Ravi
676,1136601,2018,Kolkata,5/9/2018,League,Ishan Kishan,Eden Gardens,Mumbai Indians,Kolkata Knight Riders,Kolkata Knight Riders,field,Mumbai Indians,runs,102.0,211.0,20.0,N,NaN,KN Ananthapadmanabhan,AK Chaudhary

In [41]:
df.groupby('player_of_match').size().sort_values(ascending=False).head(5)

player_of_match
CH Gayle          21
AB de Villiers    18
YK Pathan         16
RG Sharma         16
DA Warner         15
dtype: int64

In [42]:
df[df["result"] == "wickets"]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
2,335984,2007/08,Delhi,4/19/2008,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,4/20/2008,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,4/20/2008,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
5,335987,2007/08,Jaipur,4/21/2008,League,SR Watson,Sawai Mansingh Stadium,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,bat,Rajasthan Royals,wickets,6.0,167.0,20.0,N,NaN,Aleem Dar,RB Tiffin
6,335988,2007/08,Hyderabad,4/22/2008,League,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,Delhi Daredevils,wickets,9.0,143.0,20.0,N,NaN,IL Howell,AM Saheba
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1136620,2018,Mumbai,5/27/2018,Final,SR Watson,Wankhede Stadium,Sunrisers Hyderabad,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,8.0,179.0,20.0,N,NaN,M Erasmus,S Ravi
696,1175356,2019,Chennai,3/23/2019,League,Harbhajan Singh,MA Chidambaram Stadium,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,7.0,71.0,20.0,N,NaN,AY Dandekar,BNJ Oxenford
697,1175357,2019,Kolkata,3/24/2019,League,AD Russell,Eden Gardens,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,wickets,6.0,182.0,20.0,N,NaN,AK Chaudhary,CB Gaffaney
700,1175360,2019,Delhi,3/26/2019,League,SR Watson,Arun Jaitley Stadium,Delhi Capitals,Chennai Super Kings,Delhi Capitals,bat,Chennai Super Kings,wickets,6.0,148.0,20.0,N,NaN,M Erasmus,Nitin Menon
703,1175363,2019,Hyderabad,3/29/2019,League,Rashid Khan,Rajiv Gandhi International Stadium,Rajasthan Royals,Sunrisers Hyderabad,Rajasthan Royals,bat,Sunrisers Hyderabad,wickets,5.0,199.0,20.0,N,NaN,BNJ Oxenford,C Shamshuddin

In [43]:
df["city"].value_counts().head(1)

city
Mumbai    95
Name: count, dtype: int64

In [45]:
df.groupby('venue').size().sort_values(ascending=False)

venue
Eden Gardens                                            72
Wankhede Stadium                                        67
M Chinnaswamy Stadium                                   65
Feroz Shah Kotla                                        60
Rajiv Gandhi International Stadium, Uppal               49
MA Chidambaram Stadium, Chepauk                         48
Sawai Mansingh Stadium                                  41
Punjab Cricket Association Stadium, Mohali              35
Maharashtra Cricket Association Stadium                 22
Dr DY Patil Sports Academy                              17
Subrata Roy Sahara Stadium                              16
Kingsmead                                               15
SuperSport Park                                         12
Sardar Patel Stadium, Motera                            12
Punjab Cricket Association IS Bindra Stadium, Mohali    11
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium     11
Brabourne Stadium                                       10
Saurashtra Cricket Association Stadium                  10
M.Chinnaswamy Stadium                                    9
Himachal Pradesh Cricket Association Stadium             9
Holkar Cricket Stadium                                   9
New Wanderers Stadium                                    8
Arun Jaitley Stadium                                     8
Rajiv Gandhi International Stadium                       8
Barabati Stadium                                         7
JSCA International Stadium Complex                       7
Newlands                                                 7
Sheikh Zayed Stadium                                     7
Dubai International Cricket Stadium                      7
St George's Park                                         7
Shaheed Veer Narayan Singh International Stadium         6
Sharjah Cricket Stadium                                  6
Nehru Stadium                                            5
Green Park                                               4
Punjab Cricket Association IS Bindra Stadium             3
Buffalo Park                                             3
De Beers Diamond Oval                                    3
Vidarbha Cricket Association Stadium, Jamtha             3
OUTsurance Oval                                          2
MA Chidambaram Stadium                                   2
Brabourne Stadium, Mumbai                                1
dtype: int64

In [53]:
df["toss_winner_won"] = df["toss_winner"] == df["winner"]
print(df)

          id   season        city       date match_type player_of_match  \
0     335982  2007/08   Bangalore  4/18/2008     League     BB McCullum
1     335983  2007/08  Chandigarh  4/19/2008     League      MEK Hussey
2     335984  2007/08       Delhi  4/19/2008     League     MF Maharoof
3     335985  2007/08      Mumbai  4/20/2008     League      MV Boucher
4     335986  2007/08     Kolkata  4/20/2008     League       DJ Hussey
..       ...      ...         ...        ...        ...             ...
699  1175359     2019      Jaipur  3/25/2019     League        CH Gayle
700  1175360     2019       Delhi  3/26/2019     League       SR Watson
701  1175361     2019     Kolkata  3/27/2019     League      AD Russell
702  1175362     2019   Bengaluru  3/28/2019     League       JJ Bumrah
703  1175363     2019   Hyderabad  3/29/2019     League     Rashid Khan

                                          venue                        team1  \
0                         M Chinnaswamy Stadium  Royal Challengers Bangalore
1    Punjab Cricket Association Stadium, Mohali              Kings XI Punjab
2                              Feroz Shah Kotla             Delhi Daredevils
3                              Wankhede Stadium               Mumbai Indians
4                                  Eden Gardens        Kolkata Knight Riders
..                                          ...                          ...
699                      Sawai Mansingh Stadium              Kings XI Punjab
700                        Arun Jaitley Stadium               Delhi Capitals
701                                Eden Gardens        Kolkata Knight Riders
702                       M.Chinnaswamy Stadium               Mumbai Indians
703          Rajiv Gandhi International Stadium             Rajasthan Royals

                           team2                  toss_winner  ...   result  \
0          Kolkata Knight Riders  Royal Challengers Bangalore  ...     runs
1            Chennai Super Kings          Chennai Super Kings  ...     runs
2               Rajasthan Royals             Rajasthan Royals  ...  wickets
3    Royal Challengers Bangalore               Mumbai Indians  ...  wickets
4                Deccan Chargers              Deccan Chargers  ...  wickets
..                           ...                          ...  ...      ...
699             Rajasthan Royals             Rajasthan Royals  ...     runs
700          Chennai Super Kings               Delhi Capitals  ...  wickets
701              Kings XI Punjab              Kings XI Punjab  ...     runs
702  Royal Challengers Bangalore  Royal Challengers Bangalore  ...     runs
703          Sunrisers Hyderabad             Rajasthan Royals  ...  wickets

    result_margin target_runs  target_overs  super_over  method  \
0           140.0       223.0          20.0           N     NaN
1            33.0       241.0          20.0           N     NaN
2             9.0       130.0          20.0           N     NaN
3             5.0       166.0          20.0           N     NaN
4             5.0       111.0          20.0           N     NaN
..            ...         ...           ...         ...     ...
699          14.0       185.0          20.0           N     NaN
700           6.0       148.0          20.0           N     NaN
701          28.0       219.0          20.0           N     NaN
702           6.0       188.0          20.0           N     NaN
703           5.0       199.0          20.0           N     NaN

           umpire1                umpire2 Toss_Winner_Won toss_winner_won
0        Asad Rauf            RE Koertzen           False           False
1        MR Benson             SL Shastri            True            True
2        Aleem Dar         GA Pratapkumar           False           False
3         SJ Davis              DJ Harper           False           False
4        BF Bowden            K Hariharan           False           False
..             ...                    ...             ...             ...
699  C Shamshuddin  KN Ananthapadmanabhan           False           False
700      M Erasmus            Nitin Menon           False           False
701   AK Chaudhary            VA Kulkarni           False           False
702      CK Nandan                 S Ravi           False           False
703   BNJ Oxenford          C Shamshuddin           False           False

[704 rows x 22 columns]